# Generated by Django 4.0.5 on 2022-06-15 18:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('presentation', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('room', models.IntegerField()),
                ('speakers', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'Presentations',
            },
        ),
    ]
