# Generated by Django 4.0.5 on 2022-06-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='presentation.presentation')),
            ],
            options={
                'verbose_name_plural': 'Presentation Attendees',
            },
        ),
    ]
