# Generated by Django 4.0.5 on 2022-06-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentationattendance',
            options={'verbose_name_plural': 'Presentation Attendance'},
        ),
    ]
